### ISSUE TITLE
Curso em desenvolvimento?

### ISSUE THREAD

**Issue by DouglasHennrich** [alura-cursos/financas-kotlin-parte2#1]
Procurei pelo curso de Kotlin na Alura, mas não o encontrei =/
Ele está em desenvolvimento?

**Comment by alexfelipe** [comment]
Oi Douglas, blz? O curso está em desenvolvimento sim. :smile: 

[]s

**Comment by DouglasHennrich** [comment]
Perfeito, vou ficar no aguardo!

Obrigado
